/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ZcBurgerMenu {}
}

declare global {


  interface HTMLZcBurgerMenuElement extends Components.ZcBurgerMenu, HTMLStencilElement {}
  var HTMLZcBurgerMenuElement: {
    prototype: HTMLZcBurgerMenuElement;
    new (): HTMLZcBurgerMenuElement;
  };
  interface HTMLElementTagNameMap {
    'zc-burger-menu': HTMLZcBurgerMenuElement;
  }
}

declare namespace LocalJSX {
  interface ZcBurgerMenu {}

  interface IntrinsicElements {
    'zc-burger-menu': ZcBurgerMenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'zc-burger-menu': LocalJSX.ZcBurgerMenu & JSXBase.HTMLAttributes<HTMLZcBurgerMenuElement>;
    }
  }
}


