/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ZcButton {}
}

declare global {


  interface HTMLZcButtonElement extends Components.ZcButton, HTMLStencilElement {}
  var HTMLZcButtonElement: {
    prototype: HTMLZcButtonElement;
    new (): HTMLZcButtonElement;
  };
  interface HTMLElementTagNameMap {
    'zc-button': HTMLZcButtonElement;
  }
}

declare namespace LocalJSX {
  interface ZcButton {}

  interface IntrinsicElements {
    'zc-button': ZcButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'zc-button': LocalJSX.ZcButton & JSXBase.HTMLAttributes<HTMLZcButtonElement>;
    }
  }
}


